/**
 * Global Canvas Performance Optimization for Chromium & WebKit
 * 
 * Automatically enforces { willReadFrequently: true } on all 2D canvas contexts
 * created across the entire application lifecycle (including internal scratch canvases
 * generated by pdfjs-dist and image resamplers).
 * 
 * This permanently resolves Chromium's performance diagnostic:
 * "Canvas2D: Multiple readback operations using getImageData are faster with the willReadFrequently attribute set to true"
 * and substantially accelerates CPU pixel readback and JPEG encoding during PDF compression.
 */

if (typeof window !== 'undefined') {
  // 1. Optimize HTMLCanvasElement 2D contexts
  if (typeof HTMLCanvasElement !== 'undefined' && HTMLCanvasElement.prototype) {
    const origGetContext = HTMLCanvasElement.prototype.getContext;
    HTMLCanvasElement.prototype.getContext = function (
      this: HTMLCanvasElement,
      contextId: string,
      options?: any
    ): any {
      if (contextId === '2d') {
        const enhancedOptions =
          typeof options === 'object' && options !== null
            ? { ...options, willReadFrequently: true }
            : { willReadFrequently: true };
        return origGetContext.call(this, contextId, enhancedOptions);
      }
      return origGetContext.call(this, contextId, options);
    };
  }

  // 2. Optimize OffscreenCanvas 2D contexts (used by modern worker/shading pipelines)
  if (typeof OffscreenCanvas !== 'undefined' && OffscreenCanvas.prototype) {
    const origOffscreenGetContext = OffscreenCanvas.prototype.getContext;
    OffscreenCanvas.prototype.getContext = function (
      this: OffscreenCanvas,
      contextId: any,
      options?: any
    ): any {
      if (contextId === '2d') {
        const enhancedOptions =
          typeof options === 'object' && options !== null
            ? { ...options, willReadFrequently: true }
            : { willReadFrequently: true };
        return origOffscreenGetContext.call(this, contextId, enhancedOptions);
      }
      return origOffscreenGetContext.call(this, contextId, options);
    };
  }
}

export {};
